#!/bin/bash

usage() { echo "Usage: $0 --name <kibana3> --link <elasticsearch> --port <8080>" 1>&2; exit 1; }

UNKNOWN_ARGS=""
NAME=kibana3
LINK=elasticsearch
PORT=8080
while [ "$1" != "" ] ; do
    case "$1" in
       --name) NAME="$2" ; shift 2 ;;
       --link) LINK="$2" ; shift 2 ;;
       --port) PORT="$2" ; shift 2 ;;
       *) UNKNOWN_ARGS="$UNKNOWN_ARGS $1" ; shift ;;
    esac
done

if [ "$UNKNOWN_ARGS" != "" ] ; then
	usage
	echo "UNKNOWN ARGUMENT: $UNKNOWN_ARGS"
else 
	docker run -d -name "${NAME}" -p :${PORT}:80 -link ${LINK}:es hbouvier/kibana3
fi
